{% set name = "sphinx-lint" %}
{% set version = "0.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-lint-{{ version }}.tar.gz
  sha256: 8c51ab6f5a959362ddb40c5821206bb00987fe978caf46ef5362869022a4f1a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - sphinx-lint = sphinxlint.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - regex
    - polib

test:
  imports:
    - sphinxlint
  commands:
    - pip check
    - sphinx-lint --help
    - sphinx-lint --list --verbose
  requires:
    - pip

about:
  home: https://github.com/sphinx-contrib/sphinx-lint
  summary: Check for stylistic and formal issues in .rst and .py files included in the documentation.
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CAM-Gerlach
